### PR TITLE
feat: player name

### PR DESCRIPTION
**Pull request by VarPDev**
This pull request is about to that issue: https://github.com/davidjnovak/word-hunt/issues/27

### CODE REVIEW

**Comment by VarPDev** [comment]
I can't add labels.

Labels:
- feature
- frontend
- severity:low

**Comment by VarPDev** [comment]
@davidjnovak @eddiefiv any news on this?

**Review by davidjnovak — APPROVED** [review]
Hey Pasquale, thanks for the PR -- looks good. 

I'll leave the final review up to @eddiefiv

**Review by eddiefiv — COMMENTED** [review]
Changes look good to me, leaving open for second review

**Review by eddiefiv — APPROVED** [review]
Oops it was already reviewed once, my bad

**Pull request merged**
